image: node:18

stages:
  - build
  - deploy

variables:
  PUBLIC_URL: "https://lucaberton.com"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
