/**
 * Controlled vocabulary for `event.topics` in blog frontmatter, plus what each
 * topic hub (/events/topics/<slug>/) shows: an intro, Luca's own evergreen
 * guides on the topic, and the matching offer (consulting first, see
 * docs/analytics-events.md). Hubs below MIN_TOPIC_POSTS are not generated.
 */
export interface EventOffer {
  label: string;
  blurb: string;
  href: string;
  /** Must be a target_offer accepted by scripts/validate-analytics.cjs. */
  targetOffer: string;
}

export const eventOffers: Record<string, EventOffer> = {
  ai: {
    label: 'Take the Production AI readiness check',
    blurb: 'Moving from conference demos to production AI? Eight questions show where your platform, governance and operations stand.',
    href: '/production-ai-assessment/',
    targetOffer: 'production_ai_assessment',
  },
  gpu: {
    label: 'See the multi-tenant GPU architecture',
    blurb: 'Shared GPU clusters on OpenShift AI: isolation, quotas, cost and the guardrails that keep inference platforms safe in production.',
    href: '/openshift-ai-multi-tenant-gpu-architecture/',
    targetOffer: 'openshift_ai_multi_tenant_gpu_architecture',
  },
  cloud: {
    label: 'Talk about your platform',
    blurb: 'Kubernetes, platform engineering and cloud architecture reviews for teams turning conference ideas into a platform that runs.',
    href: '/services/cloud-infrastructure/',
    targetOffer: 'services_cloud_infrastructure',
  },
  automation: {
    label: 'Plan your automation strategy',
    blurb: 'Ansible and automation at enterprise scale, from the author of the Ansible by Example books.',
    href: '/services/automation-strategy/',
    targetOffer: 'services_automation_strategy',
  },
  regulated: {
    label: 'AI infrastructure for regulated enterprises',
    blurb: 'Sovereignty, the EU AI Act, NIS2 and DORA turned into an infrastructure plan that passes an audit.',
    href: '/ai-infrastructure-consultant-regulated-enterprises/',
    targetOffer: 'ai_infrastructure_consultant_regulated_enterprises',
  },
};

export interface EventTopic {
  label: string;
  /** What belongs under this topic (used for tagging, not shown). */
  scope: string;
  /** 2-3 sentences shown at the top of the hub. */
  intro: string;
  /** Slugs of Luca's evergreen posts on the topic, shown as "Go deeper". */
  guides: string[];
  offer?: keyof typeof eventOffers;
}

export const eventTopics: Record<string, EventTopic> = {
  'ai-agents': { label: "AI Agents", scope: "AI agents and agentic workflows (agent frameworks, multi-agent, AgentOps)", intro: "This hub collects talks, demos and booth conversations on AI agents from the conferences and meetups I attend. The same questions keep coming back: how agents behave in production, how to run them on platforms teams already own, how they take on commerce and ops tasks, and what a hackathon prototype needs before it becomes a real service.", guides: ["agentic-ai-enterprise-kubernetes", "ai-agents-autonomous-infrastructure-management", "ai-agent-guardrails-production"], offer: "ai" },
  'mcp': { label: "Model Context Protocol (MCP)", scope: "Model Context Protocol (MCP servers, MCP security, A2A/ACP protocols)", intro: "Here I gather sessions, demos and hallway conversations about the Model Context Protocol and the agent protocols around it. Across AGNTCon and MCPCon, Red Hat Summit and local AI meetups, the recurring themes are how MCP servers get built, how tools and legacy systems are exposed to agents, and how access to them is secured.", guides: ["claude-code-complete-guide-hooks-mcp-sdk-2026", "google-adk-sre-agent-mcp-a2a", "a2a-python-sdk-tutorial"], offer: "ai" },
  'llm-inference': { label: "LLM Inference", scope: "LLM inference and model serving (vLLM, llm-d, Triton, KServe, KV cache, quantization)", intro: "This page collects talks and demos about serving LLMs, from vLLM and distributed inference to KServe and hardware choices. The events I attend keep returning to a few themes: serving open models on Kubernetes, how frontier model providers think about cost and latency, and what operators need to run inference reliably next to everything else on the cluster.", guides: ["vllm-vs-tgi-vs-ollama-2026", "llm-d-kubernetes-native-distributed-inference", "autoscaling-ai-inference-kubernetes"], offer: "gpu" },
  'gpu-infrastructure': { label: "GPU Infrastructure", scope: "GPU infrastructure (GPU sharing, DRA, NVIDIA operators, AI factories, GPU scheduling)", intro: "I collect sessions on GPU infrastructure here: sharing and scheduling GPUs, multi-tenant clusters, NVIDIA tooling, and the hardware underneath AI workloads. Themes that repeat across KubeCon, Red Hat Summit, RISC-V and AI meetups are how to keep expensive accelerators busy, how to share them safely between teams, and what the platform around them looks like.", guides: ["gpu-sharing-kubernetes-mig-mps-time-slicing-2026", "multi-tenant-gpu-platform-operating-model", "nvidia-gpu-operator-device-plugin-config"], offer: "gpu" },
  'mlops': { label: "MLOps", scope: "MLOps and the model lifecycle (training pipelines, Kubeflow, MLflow, evaluation, fine-tuning)", intro: "This hub gathers talks and conversations about the model lifecycle: training pipelines, evaluation, fine-tuning and running models in production. Across AI_dev, AI Tinkerers, Databricks and community MLOps meetups, the recurring themes are moving from notebooks to repeatable pipelines, and how data platforms and ML tooling fit into one workflow.", guides: ["mlops-pipeline-kubernetes-enterprise-2026", "mlops-kubeflow-on-prem-guide", "fine-tuning-vs-rag-vs-prompt-engineering"], offer: "ai" },
  'rag-vector-search': { label: "RAG and Vector Search", scope: "RAG, vector search and retrieval (embeddings, vector DBs, chunking, agent memory)", intro: "Here I collect talks and demos on retrieval: RAG pipelines, vector search, embeddings and how agents remember things. The conferences and meetups I go to keep circling the same practical questions, such as how to connect models to legacy and enterprise data, which stores to put vectors in, and how to keep retrieval useful beyond a demo.", guides: ["rag-pipeline-kubernetes-production-architecture-2026", "vector-database-kubernetes-qdrant-milvus-pgvector-2026", "rag-implementation-patterns-on-rhel-ai"], offer: "ai" },
  'ai-coding-assistants': { label: "AI Coding Assistants", scope: "AI coding assistants and AI-assisted development (Copilot, Claude Code, Cursor, vibe coding)", intro: "This page collects talks, workshops and demos on AI-assisted development, from Claude Code and Copilot to Gemini CLI and newer agentic IDEs. Across the meetups and conferences I attend, the recurring themes are how coding agents change daily workflows, what teams should put around them, and how hackathon-style experiments carry over into real projects.", guides: ["claude-code-complete-guide-hooks-mcp-sdk-2026", "github-copilot-agent-mode-vscode-complete-guide", "agentic-devops-claude-code-skills-subagents"], offer: "ai" },
  'ai-security': { label: "AI Security", scope: "AI and LLM security (prompt injection, model supply chain, red teaming, guardrails)", intro: "I collect sessions on securing AI systems here: prompt injection, agent permissions, model and tool supply chains, and guardrails. The same themes appear at AGNTCon, DevWorld, security summits and local AI meetups, namely how agents get identity and limits, what can go wrong when they act on their own, and how security teams respond.", guides: ["ai-agent-guardrails-production", "ai-security-platforms-2026", "enterprise-ai-security-hardening-rhel-ai-with-selinux-and-container-isolation"], offer: "ai" },
  'ai-governance': { label: "AI Governance", scope: "AI governance and responsible AI (ethics, bias, AI Act compliance, transparency)", intro: "This hub gathers talks and panels on responsible AI, regulation and oversight. Across AI meetups, CIO and CISO events, platform conferences and privacy sessions, the recurring themes are how to put rules around AI agents, how the EU AI Act affects engineering teams, and how privacy and transparency are handled in practice.", guides: ["ai-governance-framework-enterprise", "enterprise-ai-governance-framework-2026", "ai-model-governance-compliance"], offer: "regulated" },
  'open-source-ai': { label: "Open Source AI", scope: "Open source AI and open models (InstructLab, open weights, sovereign/national models)", intro: "Here I collect talks and demos about open models and open source AI tooling, including hackathons, community meetups and Red Hat Summit sessions. The themes that keep returning are running open weights yourself, how frontier and open models compare, and what sovereign or community-owned AI looks like for European and Asian teams.", guides: ["open-source-ai-models-2026", "fine-tuning-models-with-instructlab-on-rhel-ai", "open-source-ai-tools-roundup-2026"], offer: "ai" },
  'platform-engineering': { label: "Platform Engineering", scope: "Platform engineering and internal developer platforms (Backstage, golden paths, platform as a product)", intro: "This page collects talks, meetups and booth conversations on platform engineering and internal developer platforms. At PlatformCon, Red Hat Tech Day and the Amsterdam platform meetups, the same ideas recur: treating the platform as a product, adding AI and Kubernetes to golden paths, and how to measure whether developers actually benefit.", guides: ["platform-engineering-internal-developer-portal-2026", "platform-engineering-vs-devops-2026-differences", "platform-as-product-infra-team"], offer: "cloud" },
  'kubernetes': { label: "Kubernetes", scope: "Kubernetes operations and architecture (cluster lifecycle, scheduling, operators, multi-cluster, scale)", intro: "I collect sessions on running Kubernetes here, from cluster operations to security and scale. Across KubeCon, Cloud Native Rejekts, the Dutch community meetups and telecom events, the recurring themes are how clusters are built and upgraded, what a decade of Kubernetes has taught the community, and how it is stretched to new workloads.", guides: ["kubernetes-multi-tenancy-patterns-enterprise-2026", "kubernetes-resource-limits-requests-best-practices-2026", "kubernetes-etcd-backup-maintenance-production-2026"], offer: "cloud" },
  'openshift': { label: "OpenShift", scope: "Red Hat OpenShift (OpenShift, ACM, OpenShift AI, ARO/ROSA)", intro: "This hub gathers talks, demos and booth conversations on Red Hat OpenShift, including OpenShift AI and the cloud-managed variants. Themes that recur at Red Hat Summit, KubeCon and partner events include running AI workloads on the platform, how it handles virtualization, and how it sits next to other managed container services.", guides: ["llm-deployment-openshift-ai", "kubernetes-vs-openshift", "lessons-learned-multi-tenant-gpus-openshift-ai"], offer: "gpu" },
  'virtualization': { label: "Virtualization", scope: "Virtualization and VM migration (KubeVirt, OpenShift Virtualization, VMware exit)", intro: "Here I collect sessions on virtualization and VM migration, mostly around OpenShift Virtualization, KubeVirt and leaving VMware. At Red Hat Summit, KubeCon and the AWS modernization roadshow, the recurring themes are how teams move existing VMs onto Kubernetes platforms and what they keep running alongside containers.", guides: ["ansible-for-vmware-by-examples", "kubernetes-vs-openshift", "kubernetes-migration-strategy-enterprise-guide-2026"], offer: "cloud" },
  'observability': { label: "Observability", scope: "Observability and OpenTelemetry (metrics, logs, traces, eBPF observability, SLOs)", intro: "This page collects talks and demos on observability: OpenTelemetry, metrics, logs, traces and the vendor tools around them. The conferences and meetups I attend keep returning to rolling out telemetry at scale, how AI workloads change monitoring, and what Elastic, Datadog, ClickHouse and community groups each offer for the same problems.", guides: ["opentelemetry-kubernetes-distributed-tracing-2026", "observability-ai-kubernetes-three-layers", "grafana-vs-datadog"], offer: "cloud" },
  'sre-incidents': { label: "SRE and Incidents", scope: "SRE, reliability and incident response (postmortems, chaos, on-call, resilience)", intro: "I collect sessions on reliability and incident response here. Across the Java user group at Doctolib, RoachFest, Azure Heroes and KubeCon, the recurring themes are how teams learn from outages, how resilience is designed into data and cloud systems, and what the on-call experience looks like in practice.", guides: ["aiops-sre-that-actually-works", "event-driven-ansible-incident-response", "velero-kubernetes-backup-disaster-recovery-2026"], offer: "cloud" },
  'finops': { label: "FinOps", scope: "FinOps and cloud cost optimization", intro: "This hub gathers talks on cloud cost and FinOps. Across Cloud Optimization, sustainability meetups, platform engineering events and observability sessions, the recurring themes are how teams see where money goes, how telemetry volume and platform choices drive spend, and how cost connects to energy use.", guides: ["kubernetes-cost-optimization-kubecost-opencost-2026", "finops-kubernetes-cost-allocation-showback", "finops-ai-gpu-workloads-cost-optimization-2026"], offer: "cloud" },
  'cloud-native-security': { label: "Cloud Native Security", scope: "Cloud native and container security (zero trust, runtime security, Kubernetes attack paths, identity)", intro: "Here I collect talks and demos on cloud native and container security: zero trust, runtime protection, identity and Kubernetes attack paths. The events I attend, from AWS Activation Day to the Dutch Cloud Native meetups and security summits, keep returning to how clusters get compromised and how teams defend them in practice.", guides: ["zero-trust-kubernetes-service-mesh-opa", "falco-runtime-security-kubernetes-threat-detection-2026", "kubernetes-rbac-least-privilege-production-2026"], offer: "cloud" },
  'supply-chain-security': { label: "Supply Chain Security", scope: "Software supply chain security (SBOM, signing, Sigstore, dependency risk)", intro: "This page collects sessions on software supply chain security: SBOMs, signing, dependency risk and the trust we place in open source. The recurring themes across KubeCon, DevOpsDays, Java user groups and agent security meetups are how to verify what you run, how attacks reach build pipelines, and what regulation now asks of maintainers.", guides: ["supply-chain-security-sbom-sigstore-slsa", "cra-sbom-requirements-implementation", "open-source-trust-supply-chain"], offer: "cloud" },
  'networking-ebpf': { label: "Networking and eBPF", scope: "Cloud native networking, eBPF and service mesh (Cilium, Istio, Envoy, gateways)", intro: "I collect talks on cloud native networking, eBPF, service meshes and gateways here. Across KubeCon, Cloud Native Rejekts, the Dutch Cloud Native Day and telecom and media events, the recurring themes are how eBPF changes the data path, how gateways and meshes are chosen, and how networking supports AI traffic.", guides: ["cilium-ebpf-kubernetes-networking-security-2026", "istio-service-mesh-kubernetes-production-2026", "gateway-api-production-2026"], offer: "cloud" },
  'gitops-cicd': { label: "GitOps and CI/CD", scope: "GitOps and CI/CD (Argo CD, Flux, Tekton, GitHub Actions, release engineering)", intro: "This hub gathers talks and conversations on GitOps and CI/CD, from Argo CD and Flux to GitLab and release pipelines. Across KubeCon, community meetups and the GitLab Epic Tour, the recurring themes are how teams deploy declaratively, how pipelines scale across clusters, and how delivery tooling fits into platform work.", guides: ["enterprise-gitops-maturity-model-2026", "argo-cd-gitops-kubernetes-deployment-2026", "install-argocd-kubernetes"], offer: "cloud" },
  'ansible-automation': { label: "Ansible and Automation", scope: "Ansible and IT automation (Ansible, AAP, Event-Driven Ansible, automation at scale)", intro: "Here I collect talks, demos and booth conversations on Ansible and IT automation. From Ansible Automates London and Community Day Berlin to Red Hat Summit and Tech Day Netherlands, the recurring themes are Event-Driven Ansible, automation at scale, how the community shapes collections, and how automation meets AI and OpenShift.", guides: ["red-hat-ansible-automation", "event-driven-ansible-new-collections-platform-enhancements-2026", "hands-on-ansible-automation"], offer: "automation" },
  'infrastructure-as-code': { label: "Infrastructure as Code", scope: "Infrastructure as code (Terraform, OpenTofu, Pulumi, Crossplane, policy as code)", intro: "This page collects sessions on infrastructure as code, including Terraform, Ansible, Crossplane and configuration management. The events I attend, such as Config Management Camp, PlatformCon and Azure platform meetups, keep returning to how teams manage change declaratively, how tools overlap, and how IaC feeds into developer platforms.", guides: ["terraform-vs-opentofu-migration-guide-2026", "terraform-state-management-guide-2026", "multi-cloud-terraform-patterns"], offer: "cloud" },
  'linux': { label: "Linux", scope: "Linux and operating systems (RHEL, image mode/bootc, Fedora, kernel)", intro: "I collect talks on Linux and operating systems here: RHEL, image mode, Fedora, the kernel and community distributions. Across FOSDEM, Open Source Summit, DevConf.cz and Red Hat Summit, the recurring themes are how the OS is delivered and updated, what the open source community builds next, and how Linux runs under cloud native workloads.", guides: ["bootc-image-configuration-management-2026", "rocky-linux-vs-alma-linux", "fedora-44-cutting-edge-linux"], offer: "automation" },
  'databases': { label: "Databases", scope: "Databases (PostgreSQL, ClickHouse, MongoDB, graph databases, distributed SQL)", intro: "This hub gathers talks and demos on databases: PostgreSQL, ClickHouse, CockroachDB, MotherDuck and more. The meetups I attend keep returning to analytics at speed, distributed SQL resilience, running databases in cloud native environments, and how data stores connect to AI workloads. I keep these notes for anyone choosing a data store.", guides: ["cloudnativepg-postgresql-kubernetes-operator", "databases-kubernetes-memory-overcommit-off-production", "vector-database-kubernetes-qdrant-milvus-pgvector-2026"], offer: undefined },
  'data-engineering': { label: "Data Engineering", scope: "Data engineering and analytics platforms (Airflow, Dagster, Spark, lakehouse, Kafka, streaming)", intro: "Here I collect sessions on data engineering and analytics platforms, covering orchestration, dbt, ClickHouse, streaming and warehouse tooling. Across Amsterdam meetups and vendor events, the recurring themes are choosing between orchestrators, building pipelines that AI applications can rely on, and how analytics platforms are run in production.", guides: ["orchestrate-and-recover-real-time-data-pipelines", "stream-and-unify-data-schemas-with-cdc", "strimzi-kafka-acls-gitops-self-service"], offer: undefined },
  'developer-experience': { label: "Developer Experience", scope: "Developer experience and productivity (DevEx, tooling, inner loop, documentation)", intro: "This page collects talks on developer experience and productivity, from Java user group evenings to BitBash, BrowserStack and DevWorld. Recurring themes include the tooling developers use every day, how documentation and testing fit into the inner loop, and how teams reduce friction without adding process.", guides: ["developer-experience-metrics-devex", "devex-internal-developer-platform", "platform-as-product-infra-team"], offer: "cloud" },
  'java-jvm': { label: "Java and the JVM", scope: "Java and the JVM (OpenJDK, Spring, Quarkus, Valhalla, GraalVM)", intro: "I collect sessions on Java and the JVM here, mostly from the Amsterdam Java User Group and its hosts. The recurring themes are Project Valhalla, OpenJDK community work, how Java teams adopt AI tooling, and the practical security and developer experience topics that come up in company-hosted evenings.", guides: ["spring-reactor-reactive-java-2026", "jdbc-virtual-threads-hibernate-java-problems", "building-reliable-ai-agents-java-langchain4j-workshop-2026"], offer: undefined },
  'rust': { label: "Rust", scope: "Rust", intro: "This hub gathers talks from Rust meetups in Amsterdam and Europe, along with related events like Ubuntu Summit. The recurring themes are Rust for AI and systems work, how the community is organized, and how Rust sits next to newer languages and older infrastructure. These notes are for readers deciding where Rust fits in their own stack.", guides: ["rust-kubernetes-operators-kube-rs-2026", "rust-async-runtimes-tokio-2026", "rust-vs-go-infrastructure-2026"], offer: undefined },
  'programming-languages': { label: "Programming Languages", scope: "Other programming languages and runtimes (Go, Python, JavaScript/TypeScript frameworks, WebAssembly, new languages)", intro: "Here I collect talks on languages and runtimes beyond Java and Rust, including Go, JavaScript and TypeScript, Inko and WebAssembly. The Go Amsterdam, AdvancedJS and Cloudflare meetups keep returning to how language choices affect tooling, deployment targets and the day-to-day work of building services. These notes help readers compare the ecosystems side by side.", guides: ["go-programming-language-guide-2026", "rust-vs-go-infrastructure-2026", "webassembly-kubernetes-spinkube"], offer: undefined },
  'apis': { label: "APIs", scope: "APIs and API management (API design, gateways, API security, API analytics)", intro: "This page collects talks on API design, gateways, security and analytics. Across Apidays, Nordic APIs, DevWorld and AWS Summit, the recurring themes are how APIs are protected, how they are exposed to AI agents, and the debate over when MCP is the right interface. These notes cover both the design side and the operations side.", guides: ["enterprise-api-gateway-kubernetes-comparison-2026", "gateway-api-production-2026", "kong-vs-envoy-vs-traefik-api-gateway-2026"], offer: undefined },
  'open-source-community': { label: "Open Source Community", scope: "Open source community, governance and OSPOs (contributing, maintainers, foundations)", intro: "I collect sessions on open source community life here: foundations, maintainers, contributing and how projects are governed. From AGNTCon and MCPCon to Ansible Community Day and Config Management Camp, the recurring themes are how new projects find their footing and how communities keep contributors involved.", guides: ["open-source-trust-supply-chain", "cra-open-source-impact", "mlops-community-joins-cncf-2026"], offer: undefined },
  'digital-sovereignty': { label: "Digital Sovereignty", scope: "Digital sovereignty and European cloud (sovereign cloud, EU digital commons)", intro: "This hub gathers talks on digital sovereignty and European cloud. At Red Hat Summit, FOSDEM, KubeCon and RISC-V and AI events, the recurring themes are what control over data, software and hardware means for European organizations, and how open source and open hardware support that goal.", guides: ["digital-sovereignty-eu-cloud-strategy", "digital-sovereignty-governance-trust-architecture", "geopatriation-sovereign-tech-stacks-2026"], offer: "regulated" },
  'eu-regulation': { label: "EU Tech Regulation", scope: "EU tech regulation and compliance (Cyber Resilience Act, NIS2, DORA, EU AI Act as regulation)", intro: "Here I collect talks on EU technology regulation, including the Cyber Resilience Act, NIS2, DORA and the AI Act. The events I attend keep returning to what these rules mean for engineering teams and open source maintainers, and how privacy and security practice has to change to comply.", guides: ["cra-what-is-cyber-resilience-act", "cra-kubernetes-platform-compliance", "edge-ai-eu-ai-act-compliance"], offer: "regulated" },
  'risc-v': { label: "RISC-V", scope: "RISC-V and open hardware", intro: "This page collects talks, demos and booth conversations on RISC-V and open hardware. From FOSDEM to RISC-V Summit Europe, the recurring themes are how software support is maturing, what the ecosystem looks like for European chips, and how open hardware connects to AI and sovereignty.", guides: ["what-is-risc-v-open-isa-explained", "risc-v-european-digital-sovereignty", "risc-v-development-boards-2026-guide"], offer: undefined },
  'edge-telco': { label: "Edge and Telco", scope: "Edge computing, IoT and telco cloud native (5G, RAN, CNFs)", intro: "I collect sessions on edge computing, IoT and telco cloud native here. Across KubeCon, the Cloud Native Telecom Meetup in Japan, IBC and robotics meetups, the recurring themes are running Kubernetes close to the network, how telecom operators adopt cloud native practice, and how AI reaches robots and devices.", guides: ["edge-ai-5g-network-slicing-distributed", "edge-ai-monitoring-prometheus-grafana", "edge-ai-security-protecting-models-data"], offer: "cloud" },
  'cloud-modernization': { label: "Cloud Modernization", scope: "Cloud migration and application modernization (public cloud, .NET/Java modernization, hybrid cloud)", intro: "This hub gathers talks on cloud migration and application modernization, mostly from AWS events and KubeCon. The recurring themes are how organizations move existing workloads to the cloud, how AI assistants help with modernization work, and what modernization means in practice for startups and large enterprises.", guides: ["kubernetes-migration-strategy-enterprise-guide-2026", "enterprise-cloud-migration-kubernetes-strategy-2026"], offer: "cloud" },
  'startups': { label: "Startups", scope: "Startups, founders and product growth", intro: "Here I collect talks and conversations about startups and founders, including AI Salon, AI on the Amstel, AWS Summit and Amsterdam meetups. Recurring themes are how young companies build on AI, how they find customers, and the practical side of running a small business. These notes are written for founders and the engineers working with them.", guides: ["inference-gold-rush-ai-startups-kubernetes-2026", "cra-small-business-startup-guide", "ai-native-software-development-2026"], offer: undefined },
  'career-leadership': { label: "Careers and Leadership", scope: "Careers, leadership and engineering culture", intro: "This page collects talks on careers, leadership and engineering culture, including DevOpsDays, CTO and CIO gatherings and my own year-in-review posts. The recurring themes are how leaders approach agents and AI, how engineers grow, and what keeps the community connected across events. These notes are for engineers and leads thinking about their own next step.", guides: ["devops-roadmap-2026-skills-tools-career", "people-culture-technology-transformation", "devops-to-ai-native-infrastructure-skills-2026"], offer: undefined },
  'sustainability': { label: "Sustainable IT", scope: "Green IT and sustainable computing (carbon footprint, energy efficiency)", intro: "I collect sessions on green IT and sustainable computing here. From the Amsterdam sustainability meetups to AWS Summit and IBC, the recurring themes are measuring the footprint of infrastructure, how cost and energy use are linked, and what changes when AI workloads grow. These notes are for teams who want to act on it, not only discuss it.", guides: ["carbon-aware-kubernetes-scheduling", "sustainable-computing-green-infrastructure", "green-kubernetes-carbon-aware-scheduling"], offer: undefined },
  'media-broadcast': { label: "Media and Broadcast", scope: "Media and broadcast technology", intro: "This hub gathers my notes from IBC in Amsterdam and related media technology events. The recurring themes are how broadcasters and vendors use cloud and AI, what live production infrastructure looks like, and where I run into cloud native and open source tooling in the media industry.", guides: [], offer: undefined },
  'books-publishing': { label: "Books and Publishing", scope: "Tech books, writing and publishing (book fairs, signings)", intro: "Here I collect visits to book fairs, signings and publishing events. From KubeCon book signings to Red Hat Summit and Amsterdam meetups, the recurring themes are sharing technical books with readers, writing for practitioners, and the conversations that follow a signing. These notes are for readers curious about the writing side of my work.", guides: ["hands-on-ansible-automation"], offer: undefined },
};

/** Luca's other sites with hands-on material for a topic, shown on its hub. */
export const topicElsewhere: Record<string, { label: string; href: string }[]> = {
  'ansible-automation': [
    { label: 'Ansible Pilot: step-by-step Ansible tutorials', href: 'https://www.ansiblepilot.com/' },
    { label: 'Ansible by Example: tutorials by module and use case', href: 'https://www.ansiblebyexample.com/' },
  ],
  'platform-engineering': [
    { label: 'Platform engineering services at OpenEmpower', href: 'https://www.openempower.com/services/platform-engineering' },
  ],
  'cloud-modernization': [
    { label: 'Cloud migration services at OpenEmpower', href: 'https://www.openempower.com/services/cloud-migration' },
  ],
  'ai-governance': [
    { label: 'AI governance consulting at OpenEmpower', href: 'https://www.openempower.com/services/ai-governance-consulting' },
  ],
  'eu-regulation': [
    { label: 'DORA-compliant AI operations at OpenEmpower', href: 'https://www.openempower.com/solutions/dora-compliant-ai-operations' },
  ],
  'digital-sovereignty': [
    { label: 'AI readiness for regulated enterprises at OpenEmpower', href: 'https://www.openempower.com/solutions/ai-readiness-regulated-enterprises' },
  ],
  'ai-agents': [
    { label: 'AI operating model at OpenEmpower', href: 'https://www.openempower.com/services/ai-operating-model' },
  ],
  'ai-coding-assistants': [
    { label: 'Hands-on courses at CopyPasteLearn', href: 'https://www.copypastelearn.com/courses' },
  ],
};
